In [226]:
import numpy as np

In [227]:
x = np.float32(1.0)
x

1.0

In [228]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [229]:
z = np.arange(3,dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [230]:
z.dtype

dtype('uint8')

In [231]:
x = np.array([2,3,1,0])
x

array([2, 3, 1, 0])

In [243]:
x = np.array([2, 3, 1, 0])
x

array([2, 3, 1, 0])

In [233]:
print('Dimensions: ',x.ndim)

Dimensions:  1


In [234]:
print('Data type: ', x.dtype)

Data type:  int64


In [235]:
print('Shape: ',x.shape)

Shape:  (4,)


In [236]:
print('Size: ',x.size)

Size:  4


In [237]:
print('Item size: ',x.itemsize)

Item size:  8


In [244]:
x = x.reshape(1,x.shape[0])
x.shape

(1, 4)

In [245]:
x

array([[2, 3, 1, 0]])

In [247]:
x[0,2] = 25  # first row, second column

In [248]:
x

array([[ 2,  3, 25,  0]])

In [138]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [139]:
x[0,1]

(2+0j)

In [140]:
x.shape

(3, 2)

In [141]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [142]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np.linspace(1.,4.,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [144]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [146]:
x[0]

array([0, 1, 2, 3, 4])

In [147]:
y = np.zeros((3,4))
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [148]:
z = np.ones((4,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [149]:
p = np.full((3,3),5)
p

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [150]:
q = np.eye(5,5)
q

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [151]:
r = np.random.random((3,3))
r

array([[0.12057304, 0.08050091, 0.32770936],
       [0.88777121, 0.62931778, 0.62311251],
       [0.36211369, 0.36500381, 0.75568303]])

In [152]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [154]:
a[:10:2]

array([0, 2, 4, 6, 8])

In [155]:
a[::3]

array([0, 3, 6, 9])

In [156]:
a[2::3]

array([2, 5, 8])

In [157]:
a[5:]=20
a

array([ 0,  1,  2,  3,  4, 20, 20, 20, 20, 20])

In [158]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [159]:
a[5:] = y[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [160]:
x = np.arange(35).reshape(5,7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [161]:
x[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])