In [226]:
import numpy as np

In [227]:
x = np.float32(1.0)
x

1.0

In [228]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [229]:
z = np.arange(3,dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [230]:
z.dtype

dtype('uint8')

In [231]:
x = np.array([2,3,1,0])
x

array([2, 3, 1, 0])

In [243]:
x = np.array([2, 3, 1, 0])
x

array([2, 3, 1, 0])

In [233]:
print('Dimensions: ',x.ndim)

Dimensions:  1


In [234]:
print('Data type: ', x.dtype)

Data type:  int64


In [235]:
print('Shape: ',x.shape)

Shape:  (4,)


In [236]:
print('Size: ',x.size)

Size:  4


In [237]:
print('Item size: ',x.itemsize)

Item size:  8


In [244]:
x = x.reshape(1,x.shape[0])
x.shape

(1, 4)

In [245]:
x

array([[2, 3, 1, 0]])

In [247]:
x[0,2] = 25  # first row, second column

In [248]:
x

array([[ 2,  3, 25,  0]])

In [138]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [139]:
x[0,1]

(2+0j)

In [140]:
x.shape

(3, 2)

In [141]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [142]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np.linspace(1.,4.,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [144]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [146]:
x[0]

array([0, 1, 2, 3, 4])

In [147]:
y = np.zeros((3,4))
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [148]:
z = np.ones((4,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [149]:
p = np.full((3,3),5)
p

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [150]:
q = np.eye(5,5)
q

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [151]:
r = np.random.random((3,3))
r

array([[0.12057304, 0.08050091, 0.32770936],
       [0.88777121, 0.62931778, 0.62311251],
       [0.36211369, 0.36500381, 0.75568303]])

In [152]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a[::-1]    # Reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [154]:
a[:10:2]

array([0, 2, 4, 6, 8])

In [155]:
a[::3]

array([0, 3, 6, 9])

In [156]:
a[2::3]

array([2, 5, 8])

In [157]:
a[5:]=20
a

array([ 0,  1,  2,  3,  4, 20, 20, 20, 20, 20])

In [158]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [159]:
a[5:] = y[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [160]:
x = np.arange(35).reshape(5,7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [161]:
x[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [162]:
x*3

array([[  0,   3,   6,   9,  12,  15,  18],
       [ 21,  24,  27,  30,  33,  36,  39],
       [ 42,  45,  48,  51,  54,  57,  60],
       [ 63,  66,  69,  72,  75,  78,  81],
       [ 84,  87,  90,  93,  96,  99, 102]])

In [163]:
x+1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [164]:
x/3

array([[ 0.        ,  0.33333333,  0.66666667,  1.        ,  1.33333333,
         1.66666667,  2.        ],
       [ 2.33333333,  2.66666667,  3.        ,  3.33333333,  3.66666667,
         4.        ,  4.33333333],
       [ 4.66666667,  5.        ,  5.33333333,  5.66666667,  6.        ,
         6.33333333,  6.66666667],
       [ 7.        ,  7.33333333,  7.66666667,  8.        ,  8.33333333,
         8.66666667,  9.        ],
       [ 9.33333333,  9.66666667, 10.        , 10.33333333, 10.66666667,
        11.        , 11.33333333]])

In [165]:
y = x>30
y

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True]])

In [166]:
x[y]

array([31, 32, 33, 34])

In [167]:
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [168]:
a = np.array([[10,20],[30,40]],dtype=np.int64)
a

array([[10, 20],
       [30, 40]])

In [169]:
np.sum(a)

100

In [170]:
np.sum(a,axis=0)

array([40, 60])

In [171]:
np.sum(a,axis=1)

array([30, 70])

In [172]:
a

array([[10, 20],
       [30, 40]])

In [173]:
b = np.array([[50,60],[70,80]],dtype=np.int64)
b

array([[50, 60],
       [70, 80]])

In [174]:
a+b    # np.add(a,b)

array([[ 60,  80],
       [100, 120]])

In [175]:
a-b   #np.subtract(a,b)

array([[-40, -40],
       [-40, -40]])

In [176]:
a * b  #np.multiply(a,b)

array([[ 500, 1200],
       [2100, 3200]])

In [177]:
np.dot(a,b)   # Matrix multiplication

array([[1900, 2200],
       [4300, 5000]])

In [178]:
a.dot(b)

array([[1900, 2200],
       [4300, 5000]])

In [179]:
a @ b          # Matrix multiplication

array([[1900, 2200],
       [4300, 5000]])

In [180]:
a/b           #np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [181]:
a.T           #np.transpose(a)

array([[10, 30],
       [20, 40]])

In [182]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [183]:
y = np.empty_like(x)

In [184]:
y

array([[-6917529027641081856, -6917529027641081856,                   15,
                           0],
       [                   0,                    0,                    0,
                           0],
       [                   0,                    0,                    0,
                           0]])

In [185]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [188]:
x[::-1,]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [189]:
x[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [190]:
x[::-1,::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [191]:
x = np.array([[1.,2.,3.,4.],[5,6,7,8],[9,10,11,12]])
x

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [192]:
x[2,1] = np.nan
x[1,2] = np.inf
x

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., inf,  8.],
       [ 9., nan, 11., 12.]])

In [193]:
missing_boolean = np.isnan(x) | np.isinf(x)
missing_boolean

array([[False, False, False, False],
       [False, False,  True, False],
       [False,  True, False, False]])

In [194]:
x[missing_boolean] = 0
x

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  0.,  8.],
       [ 9.,  0., 11., 12.]])

In [195]:
y = x
y

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  0.,  8.],
       [ 9.,  0., 11., 12.]])

In [196]:
y[1,2] = 255
x

array([[  1.,   2.,   3.,   4.],
       [  5.,   6., 255.,   8.],
       [  9.,   0.,  11.,  12.]])

In [197]:
z = x.copy()
z

array([[  1.,   2.,   3.,   4.],
       [  5.,   6., 255.,   8.],
       [  9.,   0.,  11.,  12.]])

In [198]:
z[1,2] = 0
z

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  0.,  8.],
       [ 9.,  0., 11., 12.]])

In [199]:
x

array([[  1.,   2.,   3.,   4.],
       [  5.,   6., 255.,   8.],
       [  9.,   0.,  11.,  12.]])

In [200]:
x.flatten()    # returns a copy

array([  1.,   2.,   3.,   4.,   5.,   6., 255.,   8.,   9.,   0.,  11.,
        12.])

In [201]:
x.ravel()      # returns a reference so it is faster

array([  1.,   2.,   3.,   4.,   5.,   6., 255.,   8.,   9.,   0.,  11.,
        12.])

In [202]:
x

array([[  1.,   2.,   3.,   4.],
       [  5.,   6., 255.,   8.],
       [  9.,   0.,  11.,  12.]])

In [203]:
x.mean()

26.333333333333332

In [204]:
np.std(x)

69.04386689312494

In [205]:
np.var(x)

4767.055555555555

In [210]:
x = x[:,:3]

In [211]:
x

array([[  1.,   2.,   3.],
       [  5.,   6., 255.],
       [  9.,   0.,  11.]])

In [212]:
np.linalg.det(x)

4384.000000000006

In [213]:
np.linalg.matrix_rank(x)

3

In [214]:
x.diagonal()

array([ 1.,  6., 11.])

In [215]:
x.diagonal(offset=-1)

array([5., 0.])

In [216]:
x.trace()

18.0

In [217]:
eigenvalues, eigenvectors = np.linalg.eig(x)

In [218]:
eigenvalues,eigenvectors

(array([23.80432967 +0.j        , -2.90216484+13.25690825j,
        -2.90216484-13.25690825j]),
 array([[-0.09597136+0.j        ,  0.02706962+0.13349027j,
          0.02706962-0.13349027j],
        [-0.99309569+0.j        , -0.98862292+0.j        ,
         -0.98862292-0.j        ],
        [-0.06745704+0.j        ,  0.03398249-0.05401386j,
          0.03398249+0.05401386j]]))

In [220]:
np.linalg.inv(x)

array([[ 0.01505474, -0.00501825,  0.11222628],
       [ 0.51094891, -0.00364964, -0.05474453],
       [-0.01231752,  0.00410584, -0.00091241]])

In [221]:
np.random.seed(1)
np.random.randint(0,25,3)

array([ 5, 11, 12])

In [222]:
np.random.normal(1.0,3.0,5)    #5 samples from a Normal dist. with a mean 1.0, std. dev. 3.0 

array([-3.80516301, -3.43348871,  2.45048754,  1.56530982, -0.39405897])

In [223]:
np.random.rand(5)      # random samples from a uniform distribution

array([0.52454816, 0.44345289, 0.22957721, 0.53441391, 0.91396202])

In [224]:
np.random.rand(5,5)

array([[0.45720481, 0.43069857, 0.93912779, 0.77838924, 0.71597052],
       [0.8027575 , 0.09280081, 0.51815255, 0.86502025, 0.82914691],
       [0.82960336, 0.27304997, 0.0592432 , 0.67052804, 0.59306552],
       [0.6716541 , 0.41178788, 0.1975509 , 0.28962964, 0.14212014],
       [0.78331447, 0.41253884, 0.03417131, 0.62402999, 0.66063573]])

In [225]:
np.random.randint(0,25,3) #0 inclusive , 25 exclusive

array([15,  2, 23])

In [249]:
a = [3,2,4]
a[-1]

4