In [3]:
import numpy as np

x = np.array([1,2,3,4])
print('Dimensions: ',x.ndim)
print('Data type: ',x.dtype)
print('Shape: ',x.shape)
print('Size: ',x.size)
print('Item Size:', x.itemsize)
print('Data: ',x)

Dimensions:  1
Data type:  int64
Shape:  (4,)
Size:  4
Item Size: 8
Data:  [1 2 3 4]


In [3]:
x.shape


(4,)

In [4]:
x.dtype

dtype('int64')

In [5]:
print(x.shape)

(4,)


In [6]:
print(x.shape)
x = x.reshape(1,x.shape[0])
print(x)
print(x.shape)
print(x[0,2])

(4,)
[[1 2 3 4]]
(1, 4)
3


In [7]:
x.shape

(1, 4)

In [8]:
x[0,3]

4

In [9]:
x = np.array(np.arange(10)).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
y = np.zeros((3,4))
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
z = np.ones((4,5))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
p = np.full((3,3),5)
print(p)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [13]:
q = np.eye(5,5)
print(q)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
r = np.random.random((3,3))
print(r)

[[0.39376626 0.67976737 0.5154645 ]
 [0.17282405 0.59622902 0.13461904]
 [0.7367384  0.07517402 0.06740188]]


In [15]:
x = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(x)


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [16]:
#row
print(x[1,:])

[50 60 70 80]


In [17]:
#rows
print(x[:2,:])

[[10 20 30 40]
 [50 60 70 80]]


In [18]:
#Columns
print(x[:,2])

[ 30  70 110]


In [19]:
x

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [20]:
x*3

array([[ 30,  60,  90, 120],
       [150, 180, 210, 240],
       [270, 300, 330, 360]])

In [21]:
x

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [22]:
x/3

array([[ 3.33333333,  6.66666667, 10.        , 13.33333333],
       [16.66666667, 20.        , 23.33333333, 26.66666667],
       [30.        , 33.33333333, 36.66666667, 40.        ]])

In [23]:
x

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [28]:
y = np.array([0,3,1])

In [29]:
y

array([0, 3, 1])

In [30]:
print(x[np.arange(3),y])

[ 10  80 100]


In [31]:
print(x[np.arange(3),y] *4)

[ 40 320 400]


In [32]:
x[np.arange(3),y] *= 4

In [33]:
x

array([[ 40,  20,  30,  40],
       [ 50,  60,  70, 320],
       [ 90, 400, 110, 120]])

In [34]:
x

array([[ 40,  20,  30,  40],
       [ 50,  60,  70, 320],
       [ 90, 400, 110, 120]])

In [35]:
idx = [x > 30]

In [36]:
idx

[array([[ True, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])]

In [37]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
a[:4]

array([0, 1, 2, 3])

In [39]:
a[0:10:2]

array([0, 2, 4, 6, 8])

In [40]:
a[::3]

array([0, 3, 6, 9])

In [41]:
a[2::3]

array([2, 5, 8])

In [42]:
x = np.arange(10,20)

In [43]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
x[5:] = 20

In [45]:
x

array([10, 11, 12, 13, 14, 20, 20, 20, 20, 20])

In [46]:
y = np.arange(10,15)

In [47]:
y

array([10, 11, 12, 13, 14])

In [48]:
x[5:]=y[::-1]

In [49]:
x

array([10, 11, 12, 13, 14, 14, 13, 12, 11, 10])

In [50]:
x

array([10, 11, 12, 13, 14, 14, 13, 12, 11, 10])

In [51]:
x = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(x)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [52]:
x = [x > 30]

In [53]:
x

[array([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])]

In [55]:
x = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(x)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [56]:
y = (x > 30)

In [57]:
y

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
x[y]

array([ 40,  50,  60,  70,  80,  90, 100, 110, 120])

In [59]:
a = np.array([[10,20],[30,40]],dtype=np.int64)

In [60]:
a

array([[10, 20],
       [30, 40]])

In [61]:
b = np.array([[50,60],[70,80]],dtype=np.int64)

In [62]:
b

array([[50, 60],
       [70, 80]])

In [63]:
c = a + b
c

array([[ 60,  80],
       [100, 120]])

In [64]:
d = a * b
d

array([[ 500, 1200],
       [2100, 3200]])

In [65]:
e = a - b
e

array([[-40, -40],
       [-40, -40]])

In [66]:
np.add(a,b)

array([[ 60,  80],
       [100, 120]])

In [67]:
np.subtract(a,b)

array([[-40, -40],
       [-40, -40]])

In [68]:
np.multiply(a,b)

array([[ 500, 1200],
       [2100, 3200]])

In [69]:
np.dot(a,b)

array([[1900, 2200],
       [4300, 5000]])

In [70]:
a

array([[10, 20],
       [30, 40]])

In [71]:
b

array([[50, 60],
       [70, 80]])

In [72]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [73]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [74]:
a

array([[10, 20],
       [30, 40]])

In [75]:
b

array([[50, 60],
       [70, 80]])

In [76]:
a.dot(b)

array([[1900, 2200],
       [4300, 5000]])

In [77]:
s = np.sum(a)

In [78]:
s

100

In [79]:
s = np.sum(a,axis=0)

In [80]:
s

array([40, 60])

In [81]:
s = np.sum(a,axis=1)

In [82]:
s

array([30, 70])

In [83]:
a

array([[10, 20],
       [30, 40]])

In [84]:
a.T

array([[10, 30],
       [20, 40]])

In [85]:
np.transpose(a)

array([[10, 30],
       [20, 40]])

In [86]:
x

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [90]:
z = np.array([1,2,3,4])

In [91]:
for i in range(x.shape[0]):
    print(i)

0
1
2


In [92]:
y = np.empty_like(x)

In [93]:
y

array([[4614688418178968235, 4619192017806338731, 4621819117588971520,
        4623695617433709227],
       [4625384467293973163, 4626322717216342016, 4627260967138710869,
        4628199217061079723],
       [4629137466983448576, 4629888066921343659, 4630357191882528085,
        4630826316843712512]])

In [94]:
for i in range(x.shape[0]):
    y[i,:] = x[i,:] + z

In [95]:
y

array([[ 11,  22,  33,  44],
       [ 51,  62,  73,  84],
       [ 91, 102, 113, 124]])

In [96]:
x

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [97]:
z

array([1, 2, 3, 4])

In [98]:
x+z

array([[ 11,  22,  33,  44],
       [ 51,  62,  73,  84],
       [ 91, 102, 113, 124]])

In [1]:
x = range(1000)
%timeit [i**2 for i in x]

288 µs ± 6.22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
y = np.arange(1000)
%timeit y**2

1.02 µs ± 31.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
np.triu(np.ones((3,3)),1)

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [13]:
x,y = np.mgrid[0:5,0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [14]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [15]:
# Masked array

x = np.ma.array([1,2,3,4],mask=[0,1,0,1])
x

masked_array(data=[1, --, 3, --],
             mask=[False,  True, False,  True],
       fill_value=999999)

In [16]:
y = np.ma.array([1,2,3,4],mask =[0,1,1,1])
y

masked_array(data=[1, --, --, --],
             mask=[False,  True,  True,  True],
       fill_value=999999)

In [17]:
x+y

masked_array(data=[2, --, --, --],
             mask=[False,  True,  True,  True],
       fill_value=999999)

In [18]:
np.ma.sqrt([1,-1,2,-2])

masked_array(data=[1.0, --, 1.4142135623730951, --],
             mask=[False,  True, False,  True],
       fill_value=1e+20)

# $5x^3 + 2x^2 + 3x+1$

In [21]:
p = np.poly1d([5,2,3,1])

In [22]:
p

poly1d([5, 2, 3, 1])

In [23]:
p(0)

1

In [24]:
p(-1)

-5

In [25]:
p.roots

array([-0.02783323+0.76161505j, -0.02783323-0.76161505j,
       -0.34433354+0.j        ])

In [26]:
p.order

3

In [27]:
p = np.polynomial.Polynomial([1,3,2,5])

In [28]:
p

Polynomial([1., 3., 2., 5.], domain=[-1,  1], window=[-1,  1])

In [29]:
p(0)

1.0

In [30]:
pwd

'/Users/nayeem/Documents/UMD/MSML605/Code'

In [13]:
x = np.array([1,2,3],dtype=np.int32)
x.data

In [14]:
bytes(x.data)

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

In [16]:
# Memory address
x.__array_interface__['data'][0]

140285197750592

In [17]:
x.__array_interface__

{'data': (140285197750592, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (3,),
 'version': 3}

In [18]:
x = b'1234'

In [19]:
x

b'1234'

In [20]:
y = np.frombuffer(x, dtype=np.int8)

In [21]:
y.data

In [23]:
y.base is x

True

In [30]:
x = np.array([1,2,3,4],dtype=np.float)
x

array([1., 2., 3., 4.])

In [28]:
y = x.astype(np.int8)
y

array([1, 2, 3, 4], dtype=int8)

In [31]:
y+1

array([2, 3, 4, 5], dtype=int8)

In [32]:
y+256

array([257, 258, 259, 260], dtype=int16)

In [33]:
y+256.0

array([257., 258., 259., 260.])

In [35]:
y + np.array([256],dtype=np.int32)

array([257, 258, 259, 260], dtype=int32)

In [36]:
x = np.array([1,2,3,-999,5])

In [37]:
mx = np.ma.masked_array(x, mask=[0,0,0,1,0])

In [38]:
mx

masked_array(data=[1, 2, 3, --, 5],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [39]:
mx.mean()

2.75

In [40]:
np.mean(mx)

2.75

In [41]:
mx[1] = 9

In [42]:
x

array([   1,    9,    3, -999,    5])

In [43]:
mx[1] = np.ma.masked

In [44]:
mx

masked_array(data=[1, --, 3, --, 5],
             mask=[False,  True, False,  True, False],
       fill_value=999999)

In [45]:
mx[1] = 9

In [46]:
mx

masked_array(data=[1, 9, 3, --, 5],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [47]:
mx.mask

array([False, False, False,  True, False])

In [48]:
x2 = mx.filled(-1)

In [49]:
x2

array([ 1,  9,  3, -1,  5])

In [50]:
mx.mask = np.ma.nomask

In [51]:
mx

masked_array(data=[1, 9, 3, -999, 5],
             mask=[False, False, False, False, False],
       fill_value=999999)